language: r
cache: packages

r_packages:
  - BH
  - devtools
  - hunspell

r_github_packages:
  - jimhester/covr
  - jimhester/lintr
  - MangoTheCat/goodpractice
  - richelbilderbeek/pirouette
  - richelbilderbeek/ribir
  - ropensci/spelling

before_script:
  - Rscript -e "install.packages(\"libs/rsexpm_0.1.1.zip\", repos = NULL, type = \"source\")"
  - Rscript -e "install.packages(\"libs/hyperA_0.1.0.tar.gz\", repos = NULL, type = \"source\")"
  - if [ -f ".lintr" ]; then echo "Do use Hadley Wickham's style guide"; exit 1; fi
  # proselint
  - sudo pip install proselint
  
script:
  - travis_wait 30 R CMD build .
  - travis_wait 30 R CMD check mbd*tar.gz

after_success:
  - Rscript -e 'lintr::lint_package()'
  - travis_wait 30 Rscript -e 'covr::codecov()'
  - travis_wait 30 Rscript -e 'goodpractice::gp()'
  - proselint *.md | egrep -v "typography\.symbols\.curly_quotes"

after_failure:
  - Rscript -e 'lintr::lint_package()'
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'goodpractice::gp()'
  - proselint *.md | egrep -v "typography\.symbols\.curly_quotes"
